export const translations = {
  en: {
    // ... contactPage aur joinUsPage sections (no change here)
    contactPage: {
      title: "Contact Us",
      breadcrumbHome: "Home",
      breadcrumbCurrent: "Contact Us",
      formTitle: "Get In Touch",
      labelName: "Full Name",
      placeholderName: "Your name",
      labelEmail: "Email Address",
      placeholderEmail: "your.email@example.com",
      labelPhone: "Phone Number",
      placeholderPhone: "+91 Your Phone Number",
      labelSubject: "Subject",
      placeholderSubject: "Subject",
      labelMessage: "Your Message",
      placeholderMessage: "Your message here...",
      buttonSend: "Send Message",
      buttonSending: "Sending...",
      successTitle: "Thank You!",
      successMessage: "Your message has been sent. We will get back to you shortly.",
      infoTitle: "Contact Info",
      infoAddressTitle: "Address",
      infoAddressText: "Delhi, India",
      infoPhoneTitle: "Phone",
      infoEmailTitle: "Email",
      infoFollowTitle: "Follow Us",
    },
    joinUsPage: {
      title: "Join Our Team",
      breadcrumbCurrent: "Join Vastumaye Team",
      sectionTitle: "Vastu Solutions | Learn, Consult, Earn",
      sectionDescription: "If you are a certified Vastu, Astrology, or Numerology practitioner with a heart for dharma and a commitment to excellence, we invite you to grow with us. We are weaving a trusted network of authentic consultants across India.",
      onboardingTitle: "Seamless Onboarding. Meaningful Opportunities.",
      onboardingPrice: "Become part of our inner circle for a modest annual contribution of ₹5,000 per year.",
      step1: "Share Your Journey: Fill out the application with your details, qualifications, and experience.",
      step2: "Connect With Us: We'll schedule a one-on-one discussion to explore alignment and expertise.",
      step3: "Welcome Aboard: If your vision resonates with ours, you’re in.",
      gainTitle: "What You Gain",
      gain1Title: "Real Client Cases",
      gain1Desc: "Allocated by geography, availability, and your unique strengths.",
      gain2Title: "Exclusive Peer Circle",
      gain2Desc: "A private discussion group for learning, support, and collaboration.",
      gain3Title: "A Trusted Brand",
      gain3Desc: "Carry the Vastumaye name with pride in Delhi-NCR and beyond.",
      formLabelName: "Full Name",
      formLabelContact: "Contact Number",
      formLabelState: "State",
      formLabelAddress: "Address",
      formLabelQualifications: "Qualifications",
      formLabelExperience: "Experience (in years)",
      buttonSubmit: "Apply & Send on WhatsApp",
      buttonSubmitting: "Submitting...",
      successTitle: "Application Received!",
      successMessage: "Thank you for your interest. We will review your application and get in touch with you shortly.",
      successButton: "Submit Another Application",
    },
    liveSessionsPage: {
      title: "Live Case Discussion",
      breadcrumbCurrent: "For Students",
      sectionTitle: "Online Vastu Practice Sessions",
      sectionDescription: "Deepen your understanding and sharpen your skills by analyzing real-world Vastu cases. We provide actual home and office floor plans for a hands-on learning experience. Limited seats available to ensure personalized attention.",
      packages: [
        { title: "One Case Study", price: "₹ 1,500", description: "60-min Zoom call" },
        { title: "Three Case Studies", price: "₹ 3,000", description: "Weekend sessions" },
        { title: "Three Case Studies (Advanced)", price: "₹ 5,000", description: "Weekend sessions" },
      ],
      successMessage: "Thank you for booking! We will contact you shortly with the session details.",
      formLabelName: "Full Name",
      formLabelContact: "Contact Number",
      formLabelState: "State",
      formLabelAddress: "Address",
      formLabelQualifications: "Qualifications",
      formLabelExperience: "Experience",
      formLabelPackage: "Choose Your Package",
      buttonSubmit: "Book Now & Send on WhatsApp",
      buttonSubmitting: "Booking...",
    },
    languageSwitcher: "हिंदी",
  },
  hi: {
    // ... contactPage aur joinUsPage sections (no change here)
    contactPage: {
      title: "हमसे संपर्क करें",
      breadcrumbHome: "होम",
      breadcrumbCurrent: "हमसे संपर्क करें",
      formTitle: "संपर्क करें",
      labelName: "पूरा नाम",
      placeholderName: "आपका नाम",
      labelEmail: "ईमेल पता",
      placeholderEmail: "आपका.ईमेल@example.com",
      labelPhone: "फ़ोन नंबर",
      placeholderPhone: "+91 आपका फ़ोन नंबर",
      labelSubject: "विषय",
      placeholderSubject: "विषय",
      labelMessage: "आपका सन्देश",
      placeholderMessage: "अपना संदेश यहां लिखें...",
      buttonSend: "संदेश भेजें",
      buttonSending: "भेज रहे हैं...",
      successTitle: "धन्यवाद!",
      successMessage: "आपका संदेश भेज दिया गया है। हम शीघ्र ही आपसे संपर्क करेंगे।",
      infoTitle: "संपर्क जानकारी",
      infoAddressTitle: "पता",
      infoAddressText: "दिल्ली, भारत",
      infoPhoneTitle: "फ़ोन",
      infoEmailTitle: "ईमेल",
      infoFollowTitle: "हमें फॉलो करें",
    },
    joinUsPage: {
      title: "हमारी टीम में शामिल हों",
      breadcrumbCurrent: "वास्तुमय टीम में शामिल हों",
      sectionTitle: "वास्तु समाधान | सीखें, सलाह दें, कमाएँ",
      sectionDescription: "यदि आप धर्म के प्रति समर्पित और उत्कृष्टता के प्रति प्रतिबद्ध एक प्रमाणित वास्तु, ज्योतिष, या अंकशास्त्र व्यवसायी हैं, तो हम आपको हमारे साथ बढ़ने के लिए आमंत्रित करते हैं। हम पूरे भारत में प्रामाणिक सलाहकारों का एक विश्वसनीय नेटवर्क बना रहे हैं।",
      onboardingTitle: "सहज ऑनबोर्डिंग। सार्थक अवसर।",
      onboardingPrice: "₹5,000 प्रति वर्ष के मामूली वार्षिक योगदान के लिए हमारे इनर सर्कल का हिस्सा बनें।",
      step1: "अपनी यात्रा साझा करें: अपने विवरण, योग्यता और अनुभव के साथ आवेदन भरें।",
      step2: "हमसे जुड़ें: हम विशेषज्ञता और संरेखण का पता लगाने के लिए एक-एक चर्चा निर्धारित करेंगे।",
      step3: "स्वागत है: यदि आपकी दृष्टि हमारी दृष्टि से मेल खाती है, तो आप टीम में हैं।",
      gainTitle: "आपको क्या लाभ मिलेगा",
      gain1Title: "वास्तविक क्लाइंट केस",
      gain1Desc: "भूगोल, उपलब्धता और आपकी अनूठी शक्तियों के अनुसार आवंटित।",
      gain2Title: "विशेष सहकर्मी समूह",
      gain2Desc: "सीखने, समर्थन और सहयोग के लिए एक निजी चर्चा समूह।",
      gain3Title: "एक विश्वसनीय ब्रांड",
      gain3Desc: "दिल्ली-एनसीआर और उससे आगे गर्व के साथ वास्तुमय नाम का प्रतिनिधित्व करें।",
      formLabelName: "पूरा नाम",
      formLabelContact: "संपर्क नंबर",
      formLabelState: "राज्य",
      formLabelAddress: "पता",
      formLabelQualifications: "योग्यता",
      formLabelExperience: "अनुभव (वर्षों में)",
      buttonSubmit: "आवेदन करें और व्हाट्सएप पर भेजें",
      buttonSubmitting: "जमा हो रहा है...",
      successTitle: "आवेदन प्राप्त हुआ!",
      successMessage: "आपकी रुचि के लिए धन्यवाद। हम आपके आवेदन की समीक्षा करेंगे और शीघ्र ही आपसे संपर्क करेंगे।",
      successButton: "एक और आवेदन जमा करें",
    },
    liveSessionsPage: {
      title: "लाइव केस चर्चा",
      breadcrumbCurrent: "छात्रों के लिए",
      sectionTitle: "ऑनलाइन वास्तु अभ्यास सत्र",
      sectionDescription: "वास्तविक वास्तु मामलों का विश्लेषण करके अपनी समझ को गहरा करें और अपने कौशल को तेज करें। हम व्यावहारिक सीखने के अनुभव के लिए वास्तविक घर और कार्यालय के फ्लोर प्लान प्रदान करते हैं। व्यक्तिगत ध्यान सुनिश्चित करने के लिए सीमित सीटें उपलब्ध हैं।",
      packages: [
        { title: "एक केस स्टडी", price: "₹ 1,500", description: "60-मिनट की जूम कॉल" },
        { title: "तीन केस स्टडी", price: "₹ 3,000", description: "सप्ताहांत सत्र" },
        { title: "तीन केस स्टडी (एडवांस्ड)", price: "₹ 5,000", description: "सप्ताहांत सत्र" },
      ],
      successMessage: "बुकिंग के लिए धन्यवाद! हम शीघ्र ही सत्र विवरण के साथ आपसे संपर्क करेंगे।",
      formLabelName: "पूरा नाम",
      formLabelContact: "संपर्क नंबर",
      formLabelState: "राज्य",
      formLabelAddress: "पता",
      formLabelQualifications: "योग्यता",
      formLabelExperience: "अनुभव",
      formLabelPackage: "अपना पैकेज चुनें",
      buttonSubmit: "अभी बुक करें और व्हाट्सएप पर भेजें",
      buttonSubmitting: "बुक हो रहा है...",
    },
    languageSwitcher: "English",
  },
};